# Generated by Django 4.2.6 on 2024-05-06 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_contactus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('email_id', models.EmailField(max_length=254)),
                ('ph_num', models.IntegerField(max_length=10)),
                ('cart_items', models.JSONField()),
                ('totalAmount', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField()),
                ('payment_id', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('order_placed_time', models.DateTimeField(auto_now_add=True)),
                ('order_complete_time', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField()),
            ],
        ),
    ]
