# Generated by Django 4.2.6 on 2024-05-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ph_num',
            field=models.IntegerField(),
        ),
    ]
