# Generated by Django 4.2.6 on 2024-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_order_ph_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_complete_time',
            field=models.DateTimeField(default='NA'),
        ),
    ]
