# Generated by Django 4.2.6 on 2024-05-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_order_order_complete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_complete_time',
            field=models.DateTimeField(blank=True, default='NA', null=True),
        ),
    ]
