# Generated by Django 4.2.6 on 2024-05-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_order_order_complete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ph_num',
            field=models.CharField(max_length=10),
        ),
    ]
