# Generated by Django 4.2.6 on 2024-05-07 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0009_alter_order_ph_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
