# Generated by Django 4.2.6 on 2024-05-08 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255)),
                ('order_status', models.CharField(default='received', max_length=255)),
                ('time_status', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
