# Generated by Django 4.2.6 on 2024-05-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Received', max_length=255),
        ),
    ]
