# Generated by Django 4.2.6 on 2024-03-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('item_description', models.TextField()),
                ('item_image', models.ImageField(upload_to='item')),
                ('item_price', models.IntegerField()),
            ],
        ),
    ]
