# Generated by Django 4.2.6 on 2024-03-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_type',
            field=models.CharField(default='NA', max_length=150),
        ),
    ]
