# Generated by Django 4.2.6 on 2024-03-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_menu_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_half_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
    ]
