# Generated by Django 4.2.6 on 2024-04-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_alter_menu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='item_half_price',
        ),
    ]
