# Generated by Django 4.2.6 on 2024-04-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_remove_menu_item_half_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='num_pieces',
            field=models.IntegerField(default=0),
        ),
    ]
